# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_data',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='login_data',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='login_data',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
